dataset:
  noisy_training_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_trainset_1f
  noisy_validation_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_valset_1f
  noisy_test_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/noisy_testset_1f
  target_training_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_trainset_1f
  target_validation_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_valset_1f
  target_test_dataset_dir: /Users/vtokala/Documents/Research/di_nn/Dataset/clean_testset_1f
defaults:
- model
- training
- dataset: speech_dataset
model:
  attention: true
  avg_mode: time
  ild_weight: 0
  ipd_weight: 0
  kurt_weight: 0
  rtf_weight: 0
  snr_weight: 0
  stoi_weight: 0
  sdr_weight: 0
  mse_weight: 1
training:
  accelerator: cpu
  batch_size: 20
  learning_rate: 0.0001
  n_epochs: 20
  n_workers: 4
  pin_memory: true
  strategy: ddp_spawn
  train_checkpoint_path: null
