dataset:
  noisy_test_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Noisy_testset
  noisy_training_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Noisy_trainset
  noisy_validation_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Noisy_valset
  target_test_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Clean_testset
  target_training_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Clean_trainset
  target_validation_dataset_dir: /Users/vtokala/Documents/Research/Databases/Dataset_Binaural_2S/Clean_valset
defaults:
- model
- training
- dataset: speech_dataset
model:
  attention: false
  avg_mode: freq
  ild_weight: 1
  ipd_weight: 10
  kurt_weight: 0
  rtf_weight: 0
  snr_weight: 1
  stoi_weight: 10
training:
  accelerator: 'cpu'
  batch_size: 32
  learning_rate: 0.0001
  n_epochs: 30
  n_workers: 4
  pin_memory: true
  strategy: ddp
  train_checkpoint_path: null
