model:
  binaural: true
  loss_mode: BINAURAL # BINAURAL | 
  
  STOI_weight: 1
 
  
  rtf_weight: 0
  snr_weight: 1
  ild_weight: 0.1

  ipd_weight: 10
  stoi_weight: 10
  binaural_avg_mode: freq # time | freq | null

  use_clstm: True
  use_cbn: True
