model:
  binaural: true
  attention: true

  STOI_weight: 1
 
  
  rtf_weight: 0
  snr_weight: 1
  ild_weight: 0

  ipd_weight: 0
  stoi_weight: 0
  binaural_avg_mode: freq # time | freq | null

  use_clstm: True
  use_cbn: True
