training:
  batch_size: 32
  n_epochs: 30
  learning_rate: 0.0001
  learning_rate_decay_steps: [3, 8]
  learning_rate_decay_values: 0.5
  n_workers: 2
  checkpoint_path: /Users/vtokala/Documents/Research/di_nn/DCNN/checkpoints/weights-epoch=35-validation_loss=-0.61.ckpt 

  early_stopping:
    enabled: True
    key_to_monitor: validation_loss
    min_delta: 0.01
    patience_in_epochs: 3