training:
  batch_size: 3
  n_epochs: 20
  learning_rate: 0.0001
  learning_rate_decay_steps: [3, 8]
  learning_rate_decay_values: 0.5
  n_workers: 2
  checkpoint_path: 

  early_stopping:
    enabled: True
    key_to_monitor: validation_loss
    min_delta: 0.01
    patience_in_epochs: 3