sr: 16000
noisy_training_dataset_dir: ../input/dcnn-wgn/Noisy_trainset
noisy_validation_dataset_dir: ../input/dcnn-wgn/Noisy_valset
noisy_test_dataset_dir: ../input/dcnn-wgn/Noisy_testset
target_training_dataset_dir: ../input/dcnn-wgn/Clean_trainset
target_validation_dataset_dir:../input/dcnn-wgn/Clean_valset
target_test_dataset_dir: ../input/dcnn-wgn/Clean_testset

name: "speech_dataset"