sr: 16000
noisy_training_dataset_dir: /kaggle/input/dcnn-mnoise/Dataset_DCNN_DMND/Noisy_trainset
noisy_validation_dataset_dir: /kaggle/input/dcnn-mnoise/Dataset_DCNN_DMND/Noisy_valset
noisy_test_dataset_dir: /kaggle/working/DCNN/Dataset/noisy_testset_1f
target_training_dataset_dir: /kaggle/input/dcnn-mnoise/Dataset_DCNN_DMND/Clean_trainset
target_validation_dataset_dir: /kaggle/input/dcnn-mnoise/Dataset_DCNN_DMND/Clean_valset
target_test_dataset_dir: /kaggle/working/DCNN/Dataset/clean_testset_1f
name: "speech_dataset"

